#include "pokedex.h"

#include <stdio.h>
#include <stdlib.h>

const char *POKEMON_NAMES[] = {
    "BULBASAUR",
    "IVYSAUR",
    "VENUSAUR",
    "CHARMANDER",
    "CHARMELEON",
    "CHARIZARD",
    "SQUIRTLE",
    "WARTORTLE",
    "BLASTOISE",
    "CATERPIE",
    "METAPOD",
    "BUTTERFREE",
    "WEEDLE",
    "KAKUNA",
    "BEEDRILL",
    "PIDGEY",
    "PIDGEOTTO",
    "PIDGEOT",
    "RATTATA",
    "RATICATE",
    "SPEAROW",
    "FEAROW",
    "EKANS",
    "ARBOK",
    "PIKACHU",
    "RAICHU",
    "SANDSHREW",
    "SANDSLASH",
    "NIDORAN♀",
    "NIDORINA",
    "NIDOQUEEN",
    "NIDORAN♂",
    "NIDORINO",
    "NIDOKING",
    "CLEFAIRY",
    "CLEFABLE",
    "VULPIX",
    "NINETALES",
    "JIGGLYPUFF",
    "WIGGLYTUFF",
    "ZUBAT",
    "GOLBAT",
    "ODDISH",
    "GLOOM",
    "VILEPLUME",
    "PARAS",
    "PARASECT",
    "VENONAT",
    "VENOMOTH",
    "DIGLETT",
    "DUGTRIO",
    "MEOWTH",
    "PERSIAN",
    "PSYDUCK",
    "GOLDUCK",
    "MANKEY",
    "PRIMEAPE",
    "GROWLITHE",
    "ARCANINE",
    "POLIWAG",
    "POLIWHIRL",
    "POLIWRATH",
    "ABRA",
    "KADABRA",
    "ALAKAZAM",
    "MACHOP",
    "MACHOKE",
    "MACHAMP",
    "BELLSPROUT",
    "WEEPINBELL",
    "VICTREEBEL",
    "TENTACOOL",
    "TENTACRUEL",
    "GEODUDE",
    "GRAVELER",
    "GOLEM",
    "PONYTA",
    "RAPIDASH",
    "SLOWPOKE",
    "SLOWBRO",
    "MAGNEMITE",
    "MAGNETON",
    "FARFETCH’D",
    "DODUO",
    "DODRIO",
    "SEEL",
    "DEWGONG",
    "GRIMER",
    "MUK",
    "SHELLDER",
    "CLOYSTER",
    "GASTLY",
    "HAUNTER",
    "GENGAR",
    "ONIX",
    "DROWZEE",
    "HYPNO",
    "KRABBY",
    "KINGLER",
    "VOLTORB",
    "ELECTRODE",
    "EXEGGCUTE",
    "EXEGGUTOR",
    "CUBONE",
    "MAROWAK",
    "HITMONLEE",
    "HITMONCHAN",
    "LICKITUNG",
    "KOFFING",
    "WEEZING",
    "RHYHORN",
    "RHYDON",
    "CHANSEY",
    "TANGELA",
    "KANGASKHAN",
    "HORSEA",
    "SEADRA",
    "GOLDEEN",
    "SEAKING",
    "STARYU",
    "STARMIE",
    "MR. MIME",
    "SCYTHER",
    "JYNX",
    "ELECTABUZZ",
    "MAGMAR",
    "PINSIR",
    "TAUROS",
    "MAGIKARP",
    "GYARADOS",
    "LAPRAS",
    "DITTO",
    "EEVEE",
    "VAPOREON",
    "JOLTEON",
    "FLAREON",
    "PORYGON",
    "OMANYTE",
    "OMASTAR",
    "KABUTO",
    "KABUTOPS",
    "AERODACTYL",
    "SNORLAX",
    "ARTICUNO",
    "ZAPDOS",
    "MOLTRES",
    "DRATINI",
    "DRAGONAIR",
    "DRAGONITE",
    "MEWTWO",
    "MEW",
    "CHIKORITA",
    "BAYLEEF",
    "MEGANIUM",
    "CYNDAQUIL",
    "QUILAVA",
    "TYPHLOSION",
    "TOTODILE",
    "CROCONAW",
    "FERALIGATR",
    "SENTRET",
    "FURRET",
    "HOOTHOOT",
    "NOCTOWL",
    "LEDYBA",
    "LEDIAN",
    "SPINARAK",
    "ARIADOS",
    "CROBAT",
    "CHINCHOU",
    "LANTURN",
    "PICHU",
    "CLEFFA",
    "IGGLYBUFF",
    "TOGEPI",
    "TOGETIC",
    "NATU",
    "XATU",
    "MAREEP",
    "FLAAFFY",
    "AMPHAROS",
    "BELLOSSOM",
    "MARILL",
    "AZUMARILL",
    "SUDOWOODO",
    "POLITOED",
    "HOPPIP",
    "SKIPLOOM",
    "JUMPLUFF",
    "AIPOM",
    "SUNKERN",
    "SUNFLORA",
    "YANMA",
    "WOOPER",
    "QUAGSIRE",
    "ESPEON",
    "UMBREON",
    "MURKROW",
    "SLOWKING",
    "MISDREAVUS",
    "UNOWN",
    "WOBBUFFET",
    "GIRAFARIG",
    "PINECO",
    "FORRETRESS",
    "DUNSPARCE",
    "GLIGAR",
    "STEELIX",
    "SNUBBULL",
    "GRANBULL",
    "QWILFISH",
    "SCIZOR",
    "SHUCKLE",
    "HERACROSS",
    "SNEASEL",
    "TEDDIURSA",
    "URSARING",
    "SLUGMA",
    "MAGCARGO",
    "SWINUB",
    "PILOSWINE",
    "CORSOLA",
    "REMORAID",
    "OCTILLERY",
    "DELIBIRD",
    "MANTINE",
    "SKARMORY",
    "HOUNDOUR",
    "HOUNDOOM",
    "KINGDRA",
    "PHANPY",
    "DONPHAN",
    "PORYGON2",
    "STANTLER",
    "SMEARGLE",
    "TYROGUE",
    "HITMONTOP",
    "SMOOCHUM",
    "ELEKID",
    "MAGBY",
    "MILTANK",
    "BLISSEY",
    "RAIKOU",
    "ENTEI",
    "SUICUNE",
    "LARVITAR",
    "PUPITAR",
    "TYRANITAR",
    "LUGIA",
    "HO-OH",
    "CELEBI",
};

void PokedexInit(Pokedex *pokedex)
{
    pokedex->registered = (unsigned short *)malloc(POKEMON_COUNT * VARIANT_COUNT * sizeof(unsigned short));
    if (pokedex->registered == NULL)
    {
        fprintf(stderr, "Failed to allocate memory for Pokedex.\n");
        exit(1);
    }
    for (unsigned int i = 0; i < POKEMON_COUNT * VARIANT_COUNT; i++)
    {
        pokedex->registered[i] = POKEDEX_NEVER_SEEN;
    }
}

void PokedexSeen(Pokedex *pokedex, unsigned int pokemonId, unsigned short variant)
{
    if (pokemonId >= POKEMON_COUNT || variant >= VARIANT_COUNT)
        return;

    unsigned int index = pokemonId * VARIANT_COUNT + variant;
    if (pokedex->registered[index] == POKEDEX_NEVER_SEEN)
    {
        pokedex->registered[index] = POKEDEX_SEEN;
    }
}

void PokedexRegister(Pokedex *pokedex, unsigned int pokemonId, unsigned short variant)
{
    if (pokemonId >= POKEMON_COUNT || variant >= VARIANT_COUNT)
        return;

    unsigned int index = pokemonId * VARIANT_COUNT + variant;
    pokedex->registered[index] = POKEDEX_REGISTERED;
}

void PokedexUnload(Pokedex *pokedex)
{
    free(pokedex->registered);
}