name: Build and Release Raylib Project

permissions:
  contents: write

on:
  push:
    branches: ["main", "master"]
    tags: ["v*"] # Trigger on version tags
  pull_request:
    branches: ["main", "master"]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: egor-tensin/setup-mingw@v3
        with:
          platform: x64
      - name: Build
        shell: bash
        run: |
          cd build
          ./premake5.exe ecc
          ./premake5.exe gmake
          cd ..
          mingw32-make.exe config=release_x64
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-bin
          path: bin/Release/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd build
          chmod +x premake5.osx
          ./premake5.osx ecc
          ./premake5.osx gmake
          cd ..
          make config=release_arm64
      - name: Upload MacOS Build
        uses: actions/upload-artifact@v4
        with:
          name: macos-bin
          path: bin/Release/

  # build-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build
  #       run: |
  #         cd build
  #         chmod +x premake5
  #         ./premake5 ecc
  #         ./premake5 gmake
  #         cd ..
  #         make config=release_x64
  #     - name: Upload Linux Build
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: linux-bin

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Package Resources
        run: zip -r resources.zip resources/

      - name: Package Windows
        run: |
          mkdir windows-dist
          cp -r windows-bin/* windows-dist/
          cd windows-dist
          zip -r pokestroke-windows.zip .
          mv pokestroke-windows.zip ../

      - name: Package MacOS
        run: |
          mkdir macos-dist
          cp -r macos-bin/* macos-dist/
          cd macos-dist
          zip -r pokestroke-macos.zip .
          mv pokestroke-macos.zip ../

      # - name: Package Linux
      #   run: |
      #     mkdir linux-dist
      #     cp -r linux-bin/* linux-dist/
      #     cd linux-dist
      #     zip -r pokestroke-linux.zip .
      #     mv pokestroke-linux.zip ../

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pokestroke-windows.zip
            pokestroke-macos.zip
            resources.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
