name: Build Raylib Project

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v3
        with:
          platform: x64

      - name: Generate build files with Premake
        shell: bash
        run: |
          cd build
          ./premake5.exe ecc
          ./premake5.exe gmake

      - name: Build Project
        shell: bash
        run: |
          mingw32-make.exe config=release_x64

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: bin/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Makefiles
        run: |
          cd build
          chmod +x premake5.osx
          ./premake5.osx ecc
          ./premake5.osx gmake

      - name: Build Project
        run: make config=release_arm64

      - name: Upload MacOS Build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: bin/
