name: Build and Release Raylib Project

permissions:
  contents: write

on:
  push:
    branches: ["main", "master"]
    tags: ["v*"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: egor-tensin/setup-mingw@v3
        with:
          platform: x64
      - name: Build
        shell: bash
        run: |
          cd build
          ./premake5.exe ecc
          ./premake5.exe gmake
          cd ..
          mingw32-make.exe config=release_x64

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-bin
          path: bin/Release/

      - name: Package MSIX
        shell: powershell
        run: |
          ./ci/package_msix.ps1

      - name: Upload MSIX Package
        uses: actions/upload-artifact@v4
        with:
          name: windows-msix
          path: Pokestroke.msix

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd build
          chmod +x premake5.osx
          ./premake5.osx ecc
          ./premake5.osx gmake
          cd ..
          make config=release_arm64

      - name: Package .app Bundle
        run: |
          chmod +x ci/package-macos-app.sh
          ./ci/package-macos-app.sh
          # Zip the .app folder specifically
          zip -r Pokestroke.app.zip Pokestroke.app

      - name: Upload MacOS Binaries
        uses: actions/upload-artifact@v4
        with:
          name: macos-bin
          path: bin/Release/

      - name: Upload MacOS App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: Pokestroke.app
          path: Pokestroke.app.zip

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Prepare Windows Release
        run: |
          mkdir windows-dist
          cp -r windows-bin/* windows-dist/
          zip -r pokestroke-windows-bin.zip windows-dist/
          cp windows-msix/Pokestroke.msix Pokestroke.msix

      - name: Prepare MacOS Binary Release
        run: |
          mkdir macos-bin-dist
          cp -r macos-bin/* macos-bin-dist/
          zip -r pokestroke-macos-bin.zip macos-bin-dist/
          cp Pokestroke.app/Pokestroke.app.zip Pokestroke.app.zip

      - name: Package Resources
        run: zip -r resources.zip resources/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pokestroke-windows-bin.zip
            Pokestroke.msix
            pokestroke-macos-bin.zip
            Pokestroke.app.zip
            resources.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
